version: '3.9'

services:
  fastapi:
    build: .
    volumes:
      - .:/app
      - /app/__pycache__
      - .env:/app/.env
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
